### ISSUE TITLE
Add wrapper for GstVideoDecoder

### ISSUE THREAD

**Issue by sdroege** [sdroege/gst-plugin-rs#11]
See https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gst-plugins-base-libs-GstVideoDecoder.html

It probably makes sense to first wrap more parts libgstvideo in gstreamer-rs so that things like GstVideoCodecFrame and GstVideoInfo/Frame can possibly be directly used without writing manual bindings. https://github.com/sdroege/gstreamer-rs/issues/5

As part of this should also be a simple decoder element. Maybe just a minimal element that takes e.g. a BMP image and *decodes* it (or rather parses the header and throws away the header).

**Comment by MathieuDuponchelle** [comment]
Seeing as we don't have a gif decoder (or encoder for that matter), and there is a crate that we could use for that purpose (http://www.piston.rs/image/gif/struct.StreamingDecoder.html) , it could also be a smart choice for the example.

> As far as I can tell, there's no API in that crate for random access / seeking, it could be added though

**Comment by sdroege** [comment]
@thiblahute was looking into this

**Comment by MathieuDuponchelle** [comment]
And still is, I think he managed to display some frames yesterday :)

**Comment by thiblahute** [comment]
I have a WIP branch here: https://github.com/thiblahute/gst-plugin-rs/tree/gifdec - still need some work but it is somehow working.

**Comment by sdroege** [comment]
Any update here and for the related PRs?

**Comment by thiblahute** [comment]
I am planning to focus on that during the hackfest (as well as getting GstTranscoder merged :-))

**Comment by fengalin** [comment]
That's great! I could use this for https://github.com/sdroege/gst-plugin-rs/issues/21

**Comment by sdroege** [comment]
This is now tracked in https://gitlab.freedesktop.org/gstreamer/gst-plugin-rs/issues/11
