### ISSUE TITLE
Implement a VobSub decoder

### ISSUE THREAD

**Issue by sdroege** [sdroege/gst-plugin-rs#21]
Around https://docs.rs/vobsub/0.2.3/vobsub/, probably best as GstVideoDecoder subclass once we have it... or GstElement.

Needs some changes to expose the `&[u8]` based API that is currently internally, and accepts elementary stream packets.

The repository also has some SRT code, might be worth adding something around that too.

CC @emk who brought this to my attention on reddit

**Comment by emk** [comment]
Sounds like a fun project!

There's a couple of us working on Rust subtitle support. I have an *.srt decoder in [substudy](https://github.com/emk/substudy), and there's also a list of other people working on textual subtitle decoding in Rust. I also remember there being a few crates on crates.io for related things.

(My very long-term goal for the [subtitles-rs](https://github.com/emk/subtitles-rs) is to improve the current state of Vobsub OCR significantly, allowing automatic conversion from VobSub to SRT for major languages. Existing solutions rely on either print OCR engines (which are limited to a few languages, and which are messy to set up), or manual letter identification (which is tedious). But that's not going to be finished soon.)

**Comment by fengalin** [comment]
FWIW, I started working on this.

**Comment by sdroege** [comment]
This is now tracked in https://gitlab.freedesktop.org/gstreamer/gst-plugin-rs/issues/21
