### ISSUE TITLE
Broken repository link

### ISSUE THREAD

**Issue by ivanovaleksey** [sdroege/gst-plugin-rs#24]
Hello Sebastian,

thank you very much for your work!

I haven't wrote any Gstreamer plugins yet but I have one in a plan :)
I believe your projects will help me a lot.

I have noticed that repository like on crates.io is broken
> https://github.com/sdroege/gst-plugin-rs/gst-plugin

If you meant it to point to `gst-plugin` workspace shouldn't it be?
> https://github.com/sdroege/gst-plugin-rs/tree/master/gst-plugin

**Comment by sdroege** [comment]
Oh thanks for noticing! I'll fix that for the next upload unless you want to send a PR.

Let me know if there's anything else appearing wrong or unclear.
