### ISSUE TITLE
Youtube HLS support

### ISSUE THREAD

**Issue by wvthoog** [sdroege/gst-plugin-rs#50]
Would it be possible to implement streaming to Youtube over HLS ?  Which is needed if you'd like to stream in H265 (HEVC)

See documentation [here](https://developers.google.com/youtube/v3/live/guides/hls-ingestion)

**Comment by sdroege** [comment]
This repo is just a mirror of https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs .
