### ISSUE TITLE
rtspsrc vs fallbacksrc

### ISSUE THREAD

**Issue by MyraBaba** [sdroege/gst-plugin-rs#53]
Hi,

We loved the idea of the fallbacksrc and very needed. But our pipeline working with rtspsrc but not wrking with fallbacksrc.

`function create_rtsp_sources() {
     echo "Rtsp sources creating"
     for ((n = 0; n < $num_of_src; n++)); do
        src_name="SRC_${n}"
        src_name="${!src_name}"
        rtsp_sources+="rtspsrc async-handling=true location=$src_name name=source_$n message-forward=true ! \
                          decodebin3 ! \
            			  queue   name=custom_preprocess_q_$n leaky=no max-size-buffers=32 max-size-bytes=0 max-size-time=0 ! \
                          $decode_scale_elements ! videoconvert n-threads=8 ! \
                          video/x-raw,pixel-aspect-ratio=1/1 ! \
                          fun.sink_$n sid.src_$n ! \
                          queue   name=comp_q_$n leaky=downstream max-size-buffers=5 max-size-bytes=0 max-size-time=0 ! \
                          comp.sink_$n "
	#echo "$n --   $rtsp_sources \n\n"
     done
}
`

isnt the fallbacksrc is the same output of the rtspsrc ? 
How we can replace the rtspsrc with fallbacksrc for above pipeline ?

**Comment by sdroege** [comment]
At this point, this repo is only a mirror of https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/. Can you report it there and please also include a debug log, plus some more description what goes wrong?

**Comment by MyraBaba** [comment]
@sdroege  Hi

Thanks for information. gitlab page not accepting new user and cant submit the issue at the moment.

There is errror just prerolling and waiting
