### ISSUE TITLE
Is gst-plugin-rs 1.22 compatible with gstreamer 1.18?

### ISSUE THREAD

**Issue by MingcongQi** [sdroege/gst-plugin-rs#54]
There was no 1.18 branch for gst-plugin-rs, is there any gst-plugin-rs version compatible with gstreamer 1.18?

**Comment by sdroege** [comment]
Yes, any including `main`. You can compile all plugins that don't require a newer version with 1.14. Check the `Cargo.toml` of each plugin for details.

Also this is only a mirror, the correct repository is at https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/
