### ISSUE TITLE
Suggested 'mirror' gitlab.freedesktop.org/gstream doesn't respond

### ISSUE THREAD

**Issue by leonardosalvatore** [sdroege/gst-plugin-rs#55]
The proposed repo is offline:   https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs

Also causing build issue:
    Updating git repository `https://gitlab.freedesktop.org/gstreamer/gstreamer-rs
    warning: spurious network error (3 tries remaining): unexpected http status code: 504; class=Http (34)
    warning: spurious network error (2 tries remaining): unexpected http status code: 504; class=Http (34)
    warning: spurious network error (1 tries remaining): unexpected http status code: 504; class=Http (34)
error: failed to get `gstreamer` as a dependency of package `gst-plugin-tutorial v0.9.11 (/home/bwilma/BuildAgent/work/100b0d6fce2ffa2f/playground/gs_prestudy/webrtc/builddir/gst-plugins-rs-cross/tutorial)`

**Comment by sdroege** [comment]
Yes, gitlab.freedesktop.org is currently down. See https://floss.social/@XOrgFoundation/110966947933348638 for more details.

**Comment by leonardosalvatore** [comment]
Apparently couldn't find any info by myself.
Thank you!
