### ISSUE TITLE
webrtcsink will not connect to signaller

### ISSUE THREAD

**Issue by marios8543** [sdroege/gst-plugin-rs#56]
I have tried with both the library provided signaller as well as a custom "echo server" and running webrtcsink with gst-launch will simply never connect to the websocket. It doesn't change anything whether I provide a `signaller::uri` or not. Needless to say because of this, the usage instructions from the documentation do not work either, as it will not connect to the rust signaller (can be confirmed by no debugging message showing up whatsoever), so the webpage will not show the test stream. Am I doing something wrong or is this a known bug ?

Thanks!

**Comment by marios8543** [comment]
Just realized this moved to gitlab, closing and moving the issue there.

**Comment by sdroege** [comment]
The correct location for this repository is now at https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/ , but for such questions the GStreamer discourse is going to be more useful: https://discourse.gstreamer.org
