### ISSUE TITLE
Gstreamer does not have features: v1_14

### ISSUE THREAD

**Issue by Yutong0** [sdroege/gst-plugin-rs#57]
Hi,

I’m trying to use “whipsink”, I followed the instruction mentioned here [Fernando Jiménez Moreno / gst-plugins-rs · GitLab](https://gitlab.freedesktop.org/ferjmoreno/gst-plugins-rs) to build. When running this command cargo cbuild --manifest-path video/cdg/Cargo.tom, it produces the error
```
Error: CliError { error: Some(failed to select a version for `gstreamer`.
    ... required by package `gst-plugin-claxon v0.6.0 (/home/a/Desktop/x/gst-plugins-rs/audio/claxon)`
versions that meet the requirements `*` are: 0.23.0

the package `gst-plugin-claxon` depends on `gstreamer`, with features: `v1_14` but `gstreamer` does not have these features.
```
I have no idea how can I fix this error, I’ve searched on Google but there is no post relate to the feature of v1_14. Any help would be appreciated.

Thank you very much!

**Comment by sdroege** [comment]
That means the repository over there is very outdated. Please try again with the official one at https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/ and report there if there's still a problem.
